name: Yasca PR
on: pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                 python-version: 3.9

            - name: Install PIP Dependencies
              run: pip install -r requirements_dev.txt

            - name: Flake8 styles
              run: python -m flake8 ./yasca

            - name: Bandit security scan
              run: python -m bandit -r ./yasca

            - name: Safety dependency scan
              run: python -m safety check
